# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       gconf

# >> macros
%define glib2_version 2.25.9
# << macros

Summary:    A process-transparent configuration system
Version:    3.2.3
Release:    1
Group:      System Environment/Base
License:    LGPLv2+
URL:        http://projects.gnome.org/gconf/
Source0:    http://download.gnome.org/sources/GConf/3.1/GConf-%{version}.tar.xz
Source1:    macros.gconf2
Source100:  gconf.yaml
Patch0:     GConf-2.18.0.1-reload.patch
Patch1:     GConf-gettext.patch
Patch2:     GConf-3.2.3-init-dbus-glib-for-multithreading.patch
Requires:   /usr/bin/killall
Requires:   dbus
Requires(post): /usr/bin/gio-querymodules
Requires(post): /sbin/ldconfig
Requires(postun): /usr/bin/gio-querymodules
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(dbus-glib-1) >= 0.8
BuildRequires:  pkgconfig(glib-2.0) >= %{glib2_version}
BuildRequires:  pkgconfig(libxslt)
BuildRequires:  pkgconfig(polkit-gobject-1) >= 0.92
BuildRequires:  autoconf
BuildRequires:  automake
BuildRequires:  gettext
BuildRequires:  intltool
BuildRequires:  libtool
BuildRequires:  pkgconfig >= 0.14
Provides:   GConf-dbus = %{version}
Provides:   GConf2 = %{version}
Conflicts:   GConf-dbus <= 2.29.1
Conflicts:   GConf2 < %{version}
Obsoletes:   GConf-dbus <= 2.29.1
Obsoletes:   GConf2 < %{version}

%description
GConf is a process-transparent configuration database API used to
store user preferences. It has pluggable backends and features to
support workgroup administration.


%package devel
Summary:    Headers and libraries for GConf development
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name} = %{version}
Requires:   automake
Requires:   pkgconfig
Requires:   pkgconfig(glib-2.0) >= %{glib2_version}
Conflicts:   GConf-dbus-devel <= 2.29.1
Obsoletes:   GConf-dbus-devel <= 2.29.1

%description devel
GConf development package. Contains files needed for doing
development using GConf.


%package lang
Summary:    Translations for Gconf
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description lang
GConf translation package.



%prep
%setup -q -n GConf-%{version}

# GConf-2.18.0.1-reload.patch
%patch0 -p1
# GConf-gettext.patch
%patch1 -p1
# GConf-3.2.3-init-dbus-glib-for-multithreading.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --enable-defaults-service \
    --disable-orbit

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
mkdir -p %{buildroot}%{_sysconfdir}/gconf/schemas
mkdir -p %{buildroot}%{_sysconfdir}/gconf/gconf.xml.system
mkdir -p %{buildroot}%{_sysconfdir}/rpm/
mkdir -p %{buildroot}%{_localstatedir}/lib/rpm-state/gconf
mkdir -p %{buildroot}%{_datadir}/GConf/gsettings
mkdir -p %{buildroot}%{_sysconfdir}/profile.d

install -p -m 644 %{SOURCE1} %{buildroot}%{_sysconfdir}/rpm/
install -p -m 644 %{SOURCE2} %{buildroot}%{_sysconfdir}/profile.d/

mkdir -p %{buildroot}%{_datadir}/GConf/gsettings
# << install post


%post
/sbin/ldconfig
# >> post
if [ $1 -gt 1 ]; then
if ! fgrep -q gconf.xml.system %{_sysconfdir}/gconf/2/path; then
sed -i -e 's@xml:readwrite:$(HOME)/.gconf@&\n\n# Location for system-wide settings.\nxml:readonly:/etc/gconf/gconf.xml.system@' %{_sysconfdir}/gconf/2/path
fi
fi
[ -x %{_bindir}/gio-querymodules ] && %{_bindir}/gio-querymodules %{_libdir}/gio/modules
# << post

%postun
/sbin/ldconfig
# >> postun
[ -x %{_bindir}/gio-querymodules ] && %{_bindir}/gio-querymodules %{_libdir}/gio/modules
# << postun

%files
%defattr(-,root,root,-)
# >> files
%defattr(-, root, root)
%doc COPYING
%config(noreplace) %{_sysconfdir}/gconf/2/path
%dir %{_sysconfdir}/gconf
%dir %{_sysconfdir}/gconf/2
%dir %{_sysconfdir}/gconf/gconf.xml.defaults
%dir %{_sysconfdir}/gconf/gconf.xml.mandatory
%dir %{_sysconfdir}/gconf/gconf.xml.system
%dir %{_sysconfdir}/gconf/schemas
%{_bindir}/gconf-merge-tree
%{_bindir}/gconftool-2
%{_bindir}/gsettings-data-convert
%{_sysconfdir}/xdg/autostart/gsettings-data-convert.desktop
%{_libexecdir}/gconfd-2
%{_libdir}/*.so.*
%{_libdir}/GConf/2/*.so
%dir %{_datadir}/sgml
%{_datadir}/sgml/gconf
%{_datadir}/GConf
%dir %{_libdir}/GConf
%dir %{_libdir}/GConf/2
%{_sysconfdir}/rpm/macros.gconf2
%{_sysconfdir}/dbus-1/system.d/org.gnome.GConf.Defaults.conf
%{_libexecdir}/gconf-defaults-mechanism
%{_datadir}/polkit-1/actions/org.gnome.gconf.defaults.policy
%{_datadir}/dbus-1/system-services/org.gnome.GConf.Defaults.service
%{_datadir}/dbus-1/services/org.gnome.GConf.service
# Something else should probably own this, but I'm not sure what.
%dir %{_localstatedir}/lib/rpm-state/
%{_localstatedir}/lib/rpm-state/gconf/
%{_libdir}/gio/modules/libgsettingsgconfbackend.so
%{_mandir}/man1/gconftool-2.1.gz
%{_mandir}/man1/gsettings-data-convert.1.gz
%{_mandir}/man1/gsettings-schema-convert.1.gz
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%defattr(-, root, root)
%{_libdir}/*.so
%{_includedir}/gconf
%{_datadir}/aclocal/*.m4
%{_datadir}/gtk-doc/html/gconf
%{_libdir}/pkgconfig/*
%{_bindir}/gsettings-schema-convert
# << files devel

%files lang
%defattr(-,root,root,-)
# >> files lang
%{_datadir}/locale/*/LC_MESSAGES/*.mo
# << files lang
